### ISSUE TITLE
node-red exits after starting flows

### ISSUE THREAD

**Issue by davidoc85** [tyrrellsystems/node-red-contrib-tinkerforge#6]
After starting node-red, the program executes the flows however it brings and exception and quits.  How can this be fixed so it still loads , so that I am able to change any nodes that are not configured properly.
See following error message:
20 Oct 12:30:51 - [red] Uncaught Exception:  
20 Oct 12:30:51 - TypeError: Cannot call method 'sendRequest' of undefined  
    at BrickletPTC.getTemperature (/usr/local/lib/node_modules/node-red-contrib-
tinkerforge/node_modules/tinkerforge/lib/BrickletPTC.js:97:14)  
    at null.<anonymous> (/usr/local/lib/node_modules/node-red-contrib-tinkerforg
e/bricklets/PTC.js:46:24)  
    at wrapper [as _onTimeout](timers.js:258:14)  
    at Timer.listOnTimeout [as ontimeout](timers.js:110:15)

**Comment by hardillb** [comment]
Forced deploy with missing config values.

Look at defaulting to localhost if missing.
